### ISSUE TITLE
Remove composer install command

### ISSUE THREAD

**Issue by dereuromark** [spryker/install#6]
since this is already a pre requirement anyway, this should probably be removed here.
refs @a-sabaa issues of working with branches in core as well.

OR: At least provide a flag to disable (-n or --no-composer) etc. Useful especially for core dev.

**Comment by stereomon** [comment]
@dereuromark I will remove the composer part from our project's install configuration. Anyway the install tool offers a way to exclude certain things. Running `vendor/bin/install -x composer` will solve the problem here already.

**Comment by stereomon** [comment]
Needs fix in project.
